har:
  server:
    web:
      domain: http://192.168.3.225
      projectName: /har-unmanned-h5
      host: ${har.server.web.domain}${har.server.web.projectName}
      errorPath: ${har.server.web.host}/#/error
      homePath: ${har.server.web.host}/#/home
      indexPath: ${har.server.web.host}/#/index
    front:
      domain: http://192.168.3.225
      projectName: /har-unmanned-mfront
      host: ${har.server.front.domain}${har.server.front.projectName}
  frontProxy:   #短信平台
    url: http://192.168.3.231:8080/har-sms-front
    appId: "000092"
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCzoaDzrYqz/slmhJr1C1CAZcPTN5LqY4zgLr+ZXrYTGRHIqji7CCv0GFNbmOy/rYZ/sTDQCs2j/2gjUmutGKn1e5h4eKdJWMiMG1y6YXptzRM/RUJYpXoHqCwHyk3ox+lXsZb9LJ/BjoDNak37LIhap0cEpWLM11IR7DbTQVpvvwIDAQAB
    sms:
      template: 【汇安融】亲爱的哥们，您的验证码是{0}。如非本人操作，请忽略本短信
      optType: 0
  picPath: http://119.6.202.172:8083/har-manage/upload/mer/productInfo/


